#!/bin/bash
# Regression test for the bundle verification contract of shader_build_tool: freshness against the
# sources, the manifest, and the required-backend list of --verify-bundle.
#
# A bundle is internally consistent even when it was built from older shaders, so the bundle's own
# identity hash cannot tell fresh from stale. The manifest written next to every bundle records a
# digest of the sources it was built from, and --verify-bundle --shader-dir must fail whenever the
# sources it is given differ from that record. This script checks exactly that, plus the ways the
# manifest itself can go missing or detach from its bundle.
#
# Usage: test_bundle_freshness.sh <path/to/shader_build_tool> <path/to/src/gpu/shaders/glsl>
#
# Generates the (fast) opengl bundle only, so it also runs on machines without a Metal toolchain.

set -u

if [ $# -ne 2 ]; then
  echo "usage: $0 <shader_build_tool> <shader-dir>" >&2
  exit 2
fi
TOOL=$1
SHADER_DIR=$2
# A comment appended to an included file: the sources change, but the generated bytes may not (the
# preprocessing drops comments), so this only exercises the include closure of the digest.
INCLUDE_FILE=level1/xp_blend_colors.inc
# A function appended to a shader: unlike a comment, this changes the generated bundle bytes.
SHADER_FILE=level1/atlas_text_fill.frag

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
failures=0

# expect <name> <pass|fail> <command...>: runs the command and compares its exit status.
expect() {
  local name=$1 want=$2
  shift 2
  "$@" >"$WORK/out.txt" 2>&1
  local status=$?
  local ok=0
  if [ "$want" = pass ] && [ $status -eq 0 ]; then ok=1; fi
  if [ "$want" = fail ] && [ $status -ne 0 ]; then ok=1; fi
  if [ $ok -eq 1 ]; then
    echo "PASS  $name"
  else
    echo "FAIL  $name (exit $status, wanted $want)"
    tail -5 "$WORK/out.txt" | sed 's/^/        /'
    failures=$((failures + 1))
  fi
}

# expect_output <name> <text>: the last command's output must contain the text.
expect_output() {
  if grep -q -- "$2" "$WORK/out.txt"; then
    echo "PASS  $1"
  else
    echo "FAIL  $1 (output does not mention \"$2\")"
    tail -5 "$WORK/out.txt" | sed 's/^/        /'
    failures=$((failures + 1))
  fi
}

for required in "$INCLUDE_FILE" "$SHADER_FILE"; do
  if [ ! -f "$SHADER_DIR/$required" ]; then
    echo "FAIL  $SHADER_DIR/$required does not exist" >&2
    exit 1
  fi
done

# Fresh bundle built from the real sources.
mkdir -p "$WORK/fresh"
expect "generate a bundle and its manifest" pass \
  "$TOOL" --shader-dir "$SHADER_DIR" --out-dir "$WORK/fresh" --backends opengl --compress
expect "the manifest is written next to the bundle" pass test -f "$WORK/fresh/shader_bundle.opengl.manifest"
expect "fresh bundle passes against its own sources" pass \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR"

# Without --shader-dir the freshness comparison is skipped, and the output must say so.
expect "no --shader-dir passes" pass "$TOOL" --verify-bundle "$WORK/fresh"
expect_output "no --shader-dir says freshness was not checked" "freshness NOT checked"

# The same bundle against sources whose included file differs by one comment line is stale, even
# though regenerating would produce identical bytes: the digest is over the source text.
cp -R "$SHADER_DIR" "$WORK/edited_include"
printf '\n// freshness test edit\n' >>"$WORK/edited_include/$INCLUDE_FILE"
expect "bundle is stale when an included file changes" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$WORK/edited_include"
expect_output "the stale bundle is reported as stale" "bundle is stale"

# A bundle built from edited shader sources is fresh for them and stale for the originals.
cp -R "$SHADER_DIR" "$WORK/edited"
printf '\nfloat tgfx_freshness_probe() { return 1.0; }\n' >>"$WORK/edited/$SHADER_FILE"
mkdir -p "$WORK/edited_out"
expect "generate a bundle from the edited sources" pass \
  "$TOOL" --shader-dir "$WORK/edited" --out-dir "$WORK/edited_out" --backends opengl --compress
expect "the edit changes the generated bytes" fail \
  cmp -s "$WORK/fresh/shader_bundle.opengl.bin" "$WORK/edited_out/shader_bundle.opengl.bin"
expect "bundle built from the edited sources passes against them" pass \
  "$TOOL" --verify-bundle "$WORK/edited_out" --shader-dir "$WORK/edited"
expect "bundle built from the edited sources is stale for the originals" fail \
  "$TOOL" --verify-bundle "$WORK/edited_out" --shader-dir "$SHADER_DIR"

# A bundle without its manifest cannot be proven fresh.
mkdir -p "$WORK/no_manifest"
cp "$WORK/fresh/shader_bundle.opengl.bin" "$WORK/no_manifest/"
expect "bundle without a manifest fails" fail \
  "$TOOL" --verify-bundle "$WORK/no_manifest" --shader-dir "$SHADER_DIR"

# A different bundle dropped in next to the old manifest must not inherit its freshness claim.
mkdir -p "$WORK/swapped"
cp "$WORK/fresh/shader_bundle.opengl.manifest" "$WORK/swapped/"
cp "$WORK/edited_out/shader_bundle.opengl.bin" "$WORK/swapped/"
expect "bundle swapped under another bundle's manifest fails" fail \
  "$TOOL" --verify-bundle "$WORK/swapped" --shader-dir "$SHADER_DIR"

# --require-backends: a required bundle that is absent is a violation. Only opengl was generated
# here, so any other backend named below is genuinely missing.
expect "required backend that is present passes" pass \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends opengl
expect "a missing required backend fails" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends opengl,metal
expect_output "the missing backend is named" "metal: VIOLATION required bundle is missing"
expect "requiring only an absent backend fails even though another bundle exists" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends vulkan
expect "a misspelled backend name fails" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends opngl
expect_output "the misspelled name is reported" "unknown backend"
expect "an empty required list fails" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends ""
expect "a stale required bundle still fails" fail \
  "$TOOL" --verify-bundle "$WORK/edited_out" --shader-dir "$SHADER_DIR" --require-backends opengl
expect "absent backends outside the required list do not fail" pass \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends opengl
expect "without --require-backends a missing bundle still passes" pass \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR"
expect_output "and the output says missing bundles were not treated as violations" \
  "--require-backends not given"
mkdir -p "$WORK/empty"
expect "an empty directory fails even when nothing is required" fail \
  "$TOOL" --verify-bundle "$WORK/empty" --shader-dir "$SHADER_DIR"

if [ $failures -ne 0 ]; then
  echo "$failures check(s) failed"
  exit 1
fi
echo "all checks passed"
