#!/bin/bash
# Regression test for the bundle verification contract of shader_build_tool: freshness against the
# sources, the manifest, and the required-backend list of --verify-bundle.
#
# A bundle is internally consistent even when it was built from older shaders, so the bundle's own
# identity hash cannot tell fresh from stale. The manifest written next to every bundle records a
# digest of the sources it was built from, and --verify-bundle --shader-dir must fail whenever the
# sources it is given differ from that record. This script checks exactly that, plus the ways the
# manifest itself can go missing or detach from its bundle.
#
# Usage: test_bundle_freshness.sh <path/to/shader_build_tool> <path/to/src/gpu/shaders/glsl>
#
# Generates the (fast) opengl bundle only, so it also runs on machines without a Metal toolchain.

set -u

if [ $# -ne 2 ]; then
  echo "usage: $0 <shader_build_tool> <shader-dir>" >&2
  exit 2
fi
TOOL=$1
SHADER_DIR=$2
# A comment appended to an included file: the sources change, but the generated bytes may not (the
# preprocessing drops comments), so this only exercises the include closure of the digest.
INCLUDE_FILE=level1/xp_blend_colors.inc
# A function appended to a shader: unlike a comment, this changes the generated bundle bytes.
SHADER_FILE=level1/atlas_text_fill.frag

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
failures=0

# expect <name> <pass|fail> <command...>: runs the command and compares its exit status.
expect() {
  local name=$1 want=$2
  shift 2
  "$@" >"$WORK/out.txt" 2>&1
  local status=$?
  local ok=0
  if [ "$want" = pass ] && [ $status -eq 0 ]; then ok=1; fi
  if [ "$want" = fail ] && [ $status -ne 0 ]; then ok=1; fi
  if [ $ok -eq 1 ]; then
    echo "PASS  $name"
  else
    echo "FAIL  $name (exit $status, wanted $want)"
    tail -5 "$WORK/out.txt" | sed 's/^/        /'
    failures=$((failures + 1))
  fi
}

# expect_output <name> <text>: the last command's output must contain the text.
expect_output() {
  if grep -q -- "$2" "$WORK/out.txt"; then
    echo "PASS  $1"
  else
    echo "FAIL  $1 (output does not mention \"$2\")"
    tail -5 "$WORK/out.txt" | sed 's/^/        /'
    failures=$((failures + 1))
  fi
}

for required in "$INCLUDE_FILE" "$SHADER_FILE"; do
  if [ ! -f "$SHADER_DIR/$required" ]; then
    echo "FAIL  $SHADER_DIR/$required does not exist" >&2
    exit 1
  fi
done

# Fresh bundle built from the real sources.
mkdir -p "$WORK/fresh"
expect "generate a bundle and its manifest" pass \
  "$TOOL" --shader-dir "$SHADER_DIR" --out-dir "$WORK/fresh" --backends opengl --compress
expect "the manifest is written next to the bundle" pass test -f "$WORK/fresh/shader_bundle.opengl.manifest"
expect "fresh bundle passes against its own sources" pass \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR"

# Without --shader-dir the freshness comparison is skipped, and the output must say so.
expect "no --shader-dir passes" pass "$TOOL" --verify-bundle "$WORK/fresh"
expect_output "no --shader-dir says freshness was not checked" "freshness NOT checked"

# The same bundle against sources whose included file differs by one comment line is stale, even
# though regenerating would produce identical bytes: the digest is over the source text.
cp -R "$SHADER_DIR" "$WORK/edited_include"
printf '\n// freshness test edit\n' >>"$WORK/edited_include/$INCLUDE_FILE"
expect "bundle is stale when an included file changes" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$WORK/edited_include"
expect_output "the stale bundle is reported as stale" "bundle is stale"

# A bundle built from edited shader sources is fresh for them and stale for the originals.
cp -R "$SHADER_DIR" "$WORK/edited"
printf '\nfloat tgfx_freshness_probe() { return 1.0; }\n' >>"$WORK/edited/$SHADER_FILE"
mkdir -p "$WORK/edited_out"
expect "generate a bundle from the edited sources" pass \
  "$TOOL" --shader-dir "$WORK/edited" --out-dir "$WORK/edited_out" --backends opengl --compress
expect "the edit changes the generated bytes" fail \
  cmp -s "$WORK/fresh/shader_bundle.opengl.bin" "$WORK/edited_out/shader_bundle.opengl.bin"
expect "bundle built from the edited sources passes against them" pass \
  "$TOOL" --verify-bundle "$WORK/edited_out" --shader-dir "$WORK/edited"
expect "bundle built from the edited sources is stale for the originals" fail \
  "$TOOL" --verify-bundle "$WORK/edited_out" --shader-dir "$SHADER_DIR"

# A bundle without its manifest cannot be proven fresh.
mkdir -p "$WORK/no_manifest"
cp "$WORK/fresh/shader_bundle.opengl.bin" "$WORK/no_manifest/"
expect "bundle without a manifest fails" fail \
  "$TOOL" --verify-bundle "$WORK/no_manifest" --shader-dir "$SHADER_DIR"

# A different bundle dropped in next to the old manifest must not inherit its freshness claim.
mkdir -p "$WORK/swapped"
cp "$WORK/fresh/shader_bundle.opengl.manifest" "$WORK/swapped/"
cp "$WORK/edited_out/shader_bundle.opengl.bin" "$WORK/swapped/"
expect "bundle swapped under another bundle's manifest fails" fail \
  "$TOOL" --verify-bundle "$WORK/swapped" --shader-dir "$SHADER_DIR"

# --require-backends: a required bundle that is absent is a violation. Only opengl was generated
# here, so any other backend named below is genuinely missing.
expect "required backend that is present passes" pass \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends opengl
expect "a missing required backend fails" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends opengl,metal
expect_output "the missing backend is named" "metal: VIOLATION required bundle is missing"
expect "requiring only an absent backend fails even though another bundle exists" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends vulkan
expect "a misspelled backend name fails" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends opngl
expect_output "the misspelled name is reported" "unknown backend"
expect "an empty required list fails" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends ""
expect "a stale required bundle still fails" fail \
  "$TOOL" --verify-bundle "$WORK/edited_out" --shader-dir "$SHADER_DIR" --require-backends opengl
expect "absent backends outside the required list do not fail" pass \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" --require-backends opengl
expect "without --require-backends a missing bundle still passes" pass \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR"
expect_output "and the output says missing bundles were not treated as violations" \
  "--require-backends not given"
mkdir -p "$WORK/empty"
expect "an empty directory fails even when nothing is required" fail \
  "$TOOL" --verify-bundle "$WORK/empty" --shader-dir "$SHADER_DIR"

# Broken sources must stop the build instead of compiling a shader with a hole in it. Includes
# resolve against the top-level shader's directory, so the helper files go next to SHADER_FILE.
INCLUDE_DIR=$(dirname "$SHADER_FILE")

# copy_sources <name>: a private copy of the shader sources to break.
copy_sources() {
  cp -R "$SHADER_DIR" "$WORK/$1"
  mkdir -p "$WORK/$1_out"
}

# A missing file behind another include: the error names the whole include chain.
copy_sources missing_include
printf '#include "tgfx_test_missing.inc"\n' >"$WORK/missing_include/$INCLUDE_DIR/tgfx_test_nested.inc"
printf '\n#include "tgfx_test_nested.inc"\n' >>"$WORK/missing_include/$SHADER_FILE"
expect "a missing include fails the build" fail \
  "$TOOL" --shader-dir "$WORK/missing_include" --out-dir "$WORK/missing_include_out" \
  --backends opengl --compress
expect_output "the missing include is named" 'cannot read #include "tgfx_test_missing.inc"'
expect_output "the error shows the include chain" "tgfx_test_nested.inc -> "
expect "no bundle is written when an include is missing" fail \
  test -e "$WORK/missing_include_out/shader_bundle.opengl.bin"
expect "a missing include also fails verification" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$WORK/missing_include"
expect_output "verification reports the source error" "source error"

# Two files including each other.
copy_sources include_cycle
printf '#include "tgfx_test_cycle_b.inc"\n' >"$WORK/include_cycle/$INCLUDE_DIR/tgfx_test_cycle_a.inc"
printf '#include "tgfx_test_cycle_a.inc"\n' >"$WORK/include_cycle/$INCLUDE_DIR/tgfx_test_cycle_b.inc"
printf '\n#include "tgfx_test_cycle_a.inc"\n' >>"$WORK/include_cycle/$SHADER_FILE"
expect "an include cycle fails the build" fail \
  "$TOOL" --shader-dir "$WORK/include_cycle" --out-dir "$WORK/include_cycle_out" \
  --backends opengl --compress
expect_output "the cycle is reported as a cycle" "include cycle"

# A chain longer than the nesting limit (32) without any cycle.
copy_sources include_depth
for i in $(seq 0 39); do
  printf '#include "tgfx_test_depth_%d.inc"\n' $((i + 1)) \
    >"$WORK/include_depth/$INCLUDE_DIR/tgfx_test_depth_$i.inc"
done
: >"$WORK/include_depth/$INCLUDE_DIR/tgfx_test_depth_40.inc"
printf '\n#include "tgfx_test_depth_0.inc"\n' >>"$WORK/include_depth/$SHADER_FILE"
expect "includes nested past the limit fail the build" fail \
  "$TOOL" --shader-dir "$WORK/include_depth" --out-dir "$WORK/include_depth_out" \
  --backends opengl --compress
expect_output "the depth limit is reported" "nested deeper than"

# Including one file repeatedly is not a cycle: the guardless slot headers rely on it. An empty
# include file is legal too.
copy_sources include_repeat
: >"$WORK/include_repeat/$INCLUDE_DIR/tgfx_test_empty.inc"
printf '\n#include "tgfx_test_empty.inc"\n#include "tgfx_test_empty.inc"\n' \
  >>"$WORK/include_repeat/$SHADER_FILE"
expect "a repeated, empty include builds" pass \
  "$TOOL" --shader-dir "$WORK/include_repeat" --out-dir "$WORK/include_repeat_out" \
  --backends opengl --compress

# The stage cache must never change what is built. Every cached run is compared byte for byte with
# a --no-cache build of the same sources.
CACHE="$WORK/stage_cache"
gen() { # gen <shader-dir> <out-dir> <cache args...>
  local dir=$1 out=$2
  shift 2
  mkdir -p "$out"
  "$TOOL" --shader-dir "$dir" --out-dir "$out" --backends opengl --compress "$@"
}
# stat_of <field>: the field of the spirv line in the last command's stage-cache summary.
stat_of() {
  sed -n 's/^\[stage-cache\] spirv: .*'"$1"'=\([0-9]*\).*/\1/p' "$WORK/out.txt"
}

expect "a --no-cache build" pass gen "$SHADER_DIR" "$WORK/nocache" --no-cache
expect "--no-cache writes no cache" fail test -e "$WORK/nocache/stage_cache"
expect "a cold cached build" pass gen "$SHADER_DIR" "$WORK/cold" --cache-dir "$CACHE"
cold_executed=$(stat_of executed)
expect "the cold build matches the uncached one" pass \
  cmp "$WORK/cold/shader_bundle.opengl.bin" "$WORK/nocache/shader_bundle.opengl.bin"
expect "a warm cached build" pass gen "$SHADER_DIR" "$WORK/warm" --cache-dir "$CACHE"
warm_executed=$(stat_of executed)
expect "the warm build compiles nothing" pass test "$warm_executed" = 0
expect "the warm build matches the uncached one" pass \
  cmp "$WORK/warm/shader_bundle.opengl.bin" "$WORK/nocache/shader_bundle.opengl.bin"
expect "the warm manifest matches the uncached one" pass \
  cmp "$WORK/warm/shader_bundle.opengl.manifest" "$WORK/nocache/shader_bundle.opengl.manifest"

# Editing one shader recompiles only the stages whose input changed, and the result equals a clean
# build of the edited sources.
expect "a cached build of the edited sources" pass \
  gen "$WORK/edited" "$WORK/edited_cached" --cache-dir "$CACHE"
edited_executed=$(stat_of executed)
expect "the edit recompiles some stages" pass test "${edited_executed:-0}" -gt 0
expect "the edit does not recompile every stage" pass \
  test "${edited_executed:-0}" -lt "${cold_executed:-0}"
expect "the edited cached build matches a clean build of the edited sources" pass \
  cmp "$WORK/edited_cached/shader_bundle.opengl.bin" "$WORK/edited_out/shader_bundle.opengl.bin"

# A damaged entry is detected, recompiled and rewritten; the output does not change.
entry=$(find "$CACHE" -type f | head -1)
printf 'x' | dd of="$entry" bs=1 seek=100 conv=notrunc 2>/dev/null
expect "a build over a damaged entry" pass gen "$SHADER_DIR" "$WORK/repaired" --cache-dir "$CACHE"
damaged_corrupt=$(stat_of corrupt)
damaged_executed=$(stat_of executed)
expect "the damaged entry is reported" pass test "$damaged_corrupt" = 1
expect "the damaged entry is recompiled" pass test "$damaged_executed" = 1
expect "the build over a damaged entry matches the uncached one" pass \
  cmp "$WORK/repaired/shader_bundle.opengl.bin" "$WORK/nocache/shader_bundle.opengl.bin"
: >"$entry"
expect "a build over a truncated entry" pass gen "$SHADER_DIR" "$WORK/truncated" --cache-dir "$CACHE"
truncated_corrupt=$(stat_of corrupt)
expect "the truncated entry is reported" pass test "$truncated_corrupt" = 1
expect "the build over a truncated entry matches the uncached one" pass \
  cmp "$WORK/truncated/shader_bundle.opengl.bin" "$WORK/nocache/shader_bundle.opengl.bin"

# An unusable cache directory degrades to compiling everything instead of failing the build.
: >"$WORK/not_a_dir"
expect "an unusable cache directory still builds" pass \
  gen "$SHADER_DIR" "$WORK/no_dir" --cache-dir "$WORK/not_a_dir/cache"
expect_output "the disabled cache is reported" "stage cache disabled"
expect "the build without a usable cache matches the uncached one" pass \
  cmp "$WORK/no_dir/shader_bundle.opengl.bin" "$WORK/nocache/shader_bundle.opengl.bin"

# Regenerating identical output must leave the files alone: the build marks generation restat, so
# an untouched bundle is what stops embedding, compiling and linking. A changed file is replaced by
# a rename, which gives it a new inode, so the inode tells "rewritten" from "left alone".
inode() { ls -i "$1" | awk '{print $1}'; }
gen "$SHADER_DIR" "$WORK/same" --cache-dir "$CACHE" >/dev/null 2>&1
same_bin=$(inode "$WORK/same/shader_bundle.opengl.bin")
same_manifest=$(inode "$WORK/same/shader_bundle.opengl.manifest")
expect "regenerating identical output" pass gen "$SHADER_DIR" "$WORK/same" --cache-dir "$CACHE"
expect "an unchanged bundle is not rewritten" pass \
  test "$(inode "$WORK/same/shader_bundle.opengl.bin")" = "$same_bin"
expect "an unchanged manifest is not rewritten" pass \
  test "$(inode "$WORK/same/shader_bundle.opengl.manifest")" = "$same_manifest"
expect "regenerating from edited sources" pass gen "$WORK/edited" "$WORK/same" --cache-dir "$CACHE"
expect "a changed bundle is replaced" fail \
  test "$(inode "$WORK/same/shader_bundle.opengl.bin")" = "$same_bin"
expect "the replaced bundle equals a clean build of the edited sources" pass \
  cmp "$WORK/same/shader_bundle.opengl.bin" "$WORK/edited_out/shader_bundle.opengl.bin"
expect "the replaced bundle is fresh for the edited sources" pass \
  "$TOOL" --verify-bundle "$WORK/same" --shader-dir "$WORK/edited"
expect "no temporary files are left behind" pass \
  test -z "$(find "$WORK/same" -maxdepth 1 -name '*.tmp*')"

# The Metal platform options are validated before anything runs, and they only concern the Metal
# bundle: a non-Metal bundle stays fresh whatever they say.
expect "an unknown Metal SDK is rejected" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --metal-sdk watchos
expect_output "the unknown SDK is named" 'unknown Metal SDK "watchos"'
expect "a malformed minimum OS is rejected" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --metal-sdk iphoneos --metal-min-os "15.0; true"
expect_output "the malformed version is reported" "invalid minimum OS version"
expect "an empty-segment minimum OS is rejected" fail \
  "$TOOL" --verify-bundle "$WORK/fresh" --metal-sdk iphoneos --metal-min-os "15..0"
expect "Metal platform options leave an opengl bundle fresh" pass \
  "$TOOL" --verify-bundle "$WORK/fresh" --shader-dir "$SHADER_DIR" \
  --metal-sdk iphonesimulator --metal-min-os 15.0

if [ $failures -ne 0 ]; then
  echo "$failures check(s) failed"
  exit 1
fi
echo "all checks passed"
