# embed_shaders.cmake - Generate ShaderModuleEmbedded.inc from .glsl source files.
#
# Usage:
#   cmake -DSHADER_DIR=src/gpu/shaders \
#         -DOUTPUT_FILE=src/gpu/ShaderModuleEmbedded.inc \
#         -P embed_shaders.cmake
#
# This script reads each .glsl file listed in SHADER_MODULES and produces a C++ include file
# containing static const std::string declarations with R"GLSL()" raw string literals.

cmake_minimum_required(VERSION 3.13)

# Mapping: C++ variable name -> .glsl relative path (relative to SHADER_DIR).
# Order must match the declaration order expected by ShaderModuleRegistry.cpp.
set(SHADER_MODULES
    "kTypesGLSL=backends/tgfx_types_glsl.glsl"
    "kConstColor=fp/const_color.glsl"
    "kLinearGradientLayout=fp/linear_gradient_layout.glsl"
    "kSingleIntervalGradientColorizer=fp/single_interval_gradient_colorizer.glsl"
    "kRadialGradientLayout=fp/radial_gradient_layout.glsl"
    "kDiamondGradientLayout=fp/diamond_gradient_layout.glsl"
    "kConicGradientLayout=fp/conic_gradient_layout.glsl"
    "kAARectEffect=fp/aa_rect_effect.glsl"
    "kColorMatrix=fp/color_matrix.glsl"
    "kLuma=fp/luma.glsl"
    "kDualIntervalGradientColorizer=fp/dual_interval_gradient_colorizer.glsl"
    "kAlphaThreshold=fp/alpha_threshold.glsl"
    "kTextureGradientColorizer=fp/texture_gradient_colorizer.glsl"
    "kDeviceSpaceTextureEffect=fp/device_space_texture_effect.glsl"
    "kTextureEffect=fragment/texture_effect.frag.glsl"
    "kTiledTextureEffect=fragment/tiled_texture_effect.frag.glsl"
    "kUnrolledBinaryGradientColorizer=fragment/unrolled_binary_gradient.frag.glsl"
    "kBlendModes=common/tgfx_blend.glsl"
    "kEmptyXfer=xfer/empty_xfer.frag.glsl"
    "kPorterDuffXfer=xfer/porter_duff_xfer.frag.glsl"
    "kXfermodeEffect=fragment/xfermode.frag.glsl"
    "kClampedGradientEffect=fragment/clamped_gradient_effect.frag.glsl"
    "kGaussianBlur1D=fragment/gaussian_blur_1d.frag.glsl"
    "kColorSpaceXformEffect=fragment/color_space_xform.frag.glsl"
    "kDefaultGeometryVert=geometry/default_geometry.vert.glsl"
    "kMeshGeometryVert=geometry/mesh_geometry.vert.glsl"
    "kQuadAAGeometryVert=geometry/quad_aa_geometry.vert.glsl"
    "kAtlasTextGeometryVert=geometry/atlas_text_geometry.vert.glsl"
    "kEllipseGeometryVert=geometry/ellipse_geometry.vert.glsl"
    "kRoundStrokeRectGeometryVert=geometry/round_stroke_rect_geometry.vert.glsl"
    "kHairlineLineGeometryVert=geometry/hairline_line_geometry.vert.glsl"
    "kHairlineQuadGeometryVert=geometry/hairline_quad_geometry.vert.glsl"
    "kNonAARRectGeometryVert=geometry/non_aa_rrect_geometry.vert.glsl"
)

if(NOT DEFINED SHADER_DIR)
    message(FATAL_ERROR "SHADER_DIR is not defined. Usage: cmake -DSHADER_DIR=... -DOUTPUT_FILE=... -P embed_shaders.cmake")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is not defined. Usage: cmake -DSHADER_DIR=... -DOUTPUT_FILE=... -P embed_shaders.cmake")
endif()

# Build output content.
set(OUTPUT_CONTENT "// AUTO-GENERATED by embed_shaders.cmake from src/gpu/shaders/*.glsl\n")
string(APPEND OUTPUT_CONTENT "// DO NOT EDIT — modify the .glsl source files and re-run:\n")
string(APPEND OUTPUT_CONTENT "//   cmake -DSHADER_DIR=src/gpu/shaders -DOUTPUT_FILE=src/gpu/ShaderModuleEmbedded.inc -P embed_shaders.cmake\n\n")

foreach(ENTRY ${SHADER_MODULES})
    # Split "kVarName=relative/path.glsl" into VAR_NAME and GLSL_PATH.
    string(FIND "${ENTRY}" "=" EQ_POS)
    string(SUBSTRING "${ENTRY}" 0 ${EQ_POS} VAR_NAME)
    math(EXPR PATH_START "${EQ_POS} + 1")
    string(SUBSTRING "${ENTRY}" ${PATH_START} -1 GLSL_REL_PATH)

    set(GLSL_FULL_PATH "${SHADER_DIR}/${GLSL_REL_PATH}")

    if(NOT EXISTS "${GLSL_FULL_PATH}")
        message(FATAL_ERROR "Shader source file not found: ${GLSL_FULL_PATH}")
    endif()

    file(READ "${GLSL_FULL_PATH}" GLSL_CONTENT)

    # Strip trailing newlines to keep output clean.
    string(REGEX REPLACE "\n+$" "" GLSL_CONTENT "${GLSL_CONTENT}")

    string(APPEND OUTPUT_CONTENT "static const std::string ${VAR_NAME} = R\"GLSL(\n")
    string(APPEND OUTPUT_CONTENT "${GLSL_CONTENT}\n")
    string(APPEND OUTPUT_CONTENT ")GLSL\";\n\n")
endforeach()

file(WRITE "${OUTPUT_FILE}" "${OUTPUT_CONTENT}")

message(STATUS "Generated ${OUTPUT_FILE} with ${CMAKE_ARGC} shader modules embedded.")
