#!/usr/bin/env node
process.chdir(__dirname);

const childProcess = require("child_process");
childProcess.execSync("depsync");

process.argv.push("./");
process.argv.push("-DTGFX_BUILD_HELLO2D=ON")
let args = process.argv.slice(2);
if (args.indexOf("-p") === -1 && args.indexOf("--platform") === -1) {
    process.argv.push("-p");
    process.argv.push("mac");
}
require("../third_party/vendor_tools/xcode-gen");

// Post-process the generated pbxproj to fix CMake Xcode generator issue:
// CMake marks the app product as "compiled.mach-o.executable" but it should be
// "wrapper.application" for Xcode to recognize it as an app bundle.
const fs = require("fs");
const path = require("path");
const pbxprojPath = path.join(__dirname, "Hello2D.xcodeproj/project.pbxproj");
let pbxproj = fs.readFileSync(pbxprojPath, "utf8");
pbxproj = pbxproj.replace(
    /(\/\*\s*Hello2D\s*\*\/\s*=\s*\{isa\s*=\s*PBXFileReference;\s*)explicitFileType\s*=\s*"compiled\.mach-o\.executable"(;\s*)(path\s*=\s*)Hello2D(;)/,
    "$1explicitFileType = wrapper.application; includeInIndex = 0$2$3Hello2D.app$4"
);
fs.writeFileSync(pbxprojPath, pbxproj);
