#!/usr/bin/env node
process.chdir(__dirname);

const childProcess = require("child_process");
childProcess.execSync("depsync", {stdio: "inherit"});

const xcodeGen = require("path").resolve(__dirname, "../third_party/vendor_tools/xcode-gen");

childProcess.execSync(
    `node "${xcodeGen}" ../ -w -DTGFX_BUILD_HELLO2D=ON -DTGFX_USE_METAL=ON -p ios -o metal`,
    {stdio: "inherit"}
);

childProcess.execSync(
    `node "${xcodeGen}" ../ -w -DTGFX_BUILD_HELLO2D=ON -p ios -o opengl`,
    {stdio: "inherit"}
);
