#!/usr/bin/env node
// run 'gen_project -h" to print help message
const XCode = require("../third_party/vendor_tools/lib/XCode");
const path = require('path');
let outPath = __dirname;
let sourcePath = path.resolve(outPath, "../");
XCode.Generate(sourcePath, outPath, "ios");