if(VCPKG_TARGET_IS_WINDOWS)
    set(ORIGINAL_PATH "$ENV{PATH}")
    
    execute_process(
        COMMAND powershell -Command "[Environment]::GetEnvironmentVariable('PATH', 'Machine') + ';' + [Environment]::GetEnvironmentVariable('PATH', 'User')"
        OUTPUT_VARIABLE FULL_SYSTEM_PATH
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
        
    if(NOT FULL_SYSTEM_PATH)
        message(FATAL_ERROR "Failed to retrieve system PATH using PowerShell. Git detection cannot proceed.")
    endif()
        
    set(COMBINED_PATH "${ORIGINAL_PATH};${FULL_SYSTEM_PATH}")
    set(ENV{PATH} "${COMBINED_PATH}")
endif()

function(build_tgfx_single_config SOURCE_PATH NODEJS OUTPUT_DIR IS_DEBUG)
    set(BUILD_ARGS "${SOURCE_PATH}/build_tgfx")
    list(APPEND BUILD_ARGS --source "${SOURCE_PATH}")
    list(APPEND BUILD_ARGS --output "${OUTPUT_DIR}")

    if(IS_DEBUG)
        list(APPEND BUILD_ARGS --debug)
    endif()

    # Add TGFX feature flags based on vcpkg features
    if("enable-svg" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_BUILD_SVG=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_BUILD_SVG=OFF)
    endif()

    if("enable-pdf" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_BUILD_PDF=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_BUILD_PDF=OFF)
    endif()

    if("enable-framework" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_BUILD_FRAMEWORK=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_BUILD_FRAMEWORK=OFF)
    endif()

    if("enable-qt" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_QT=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_QT=OFF)
    endif()

    if("enable-swiftshader" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_SWIFTSHADER=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_SWIFTSHADER=OFF)
    endif()

    if("enable-angle" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_ANGLE=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_ANGLE=OFF)
    endif()

    if("enable-opengl" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_OPENGL=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_OPENGL=OFF)
    endif()

    if("enable-threads" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_THREADS=ON)
        if(VCPKG_TARGET_IS_EMSCRIPTEN)
            list(APPEND BUILD_ARGS -DEMSCRIPTEN_PTHREADS=ON)
        endif()
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_THREADS=OFF)
    endif()

    if("enable-freetype" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_FREETYPE=ON)
    else()
        if("enable-threads" IN_LIST FEATURES AND VCPKG_TARGET_IS_EMSCRIPTEN)
            list(APPEND BUILD_ARGS -DTGFX_USE_FREETYPE=ON)
        else()
            list(APPEND BUILD_ARGS -DTGFX_USE_FREETYPE=OFF)
        endif()
    endif()

    if("enable-inspector" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_INSPECTOR=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_INSPECTOR=OFF)
    endif()

    if("enable-png-decode" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_PNG_DECODE=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_PNG_DECODE=OFF)
    endif()

    if("enable-png-encode" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_PNG_ENCODE=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_PNG_ENCODE=OFF)
    endif()

    if("enable-jpeg-decode" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_JPEG_DECODE=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_JPEG_DECODE=OFF)
    endif()

    if("enable-jpeg-encode" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_JPEG_ENCODE=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_JPEG_ENCODE=OFF)
    endif()

    if("enable-webp-decode" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_WEBP_DECODE=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_WEBP_DECODE=OFF)
    endif()

    if("enable-webp-encode" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_WEBP_ENCODE=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_WEBP_ENCODE=OFF)
    endif()

    if("enable-text-gamma-correction" IN_LIST FEATURES)
        list(APPEND BUILD_ARGS -DTGFX_USE_TEXT_GAMMA_CORRECTION=ON)
    else()
        list(APPEND BUILD_ARGS -DTGFX_USE_TEXT_GAMMA_CORRECTION=OFF)
    endif()

    if(VCPKG_TARGET_IS_WINDOWS)
        list(APPEND BUILD_ARGS -p win)
    elseif(VCPKG_TARGET_IS_OSX)
        list(APPEND BUILD_ARGS -p mac)
    elseif(VCPKG_TARGET_IS_IOS)
        list(APPEND BUILD_ARGS -p ios)
    elseif(VCPKG_TARGET_IS_LINUX)
        list(APPEND BUILD_ARGS -p linux)
    elseif(VCPKG_TARGET_IS_ANDROID)
        list(APPEND BUILD_ARGS -p android)
    elseif(VCPKG_CMAKE_SYSTEM_NAME MATCHES "OHOS")
        list(APPEND BUILD_ARGS -p ohos)
    elseif(VCPKG_TARGET_IS_EMSCRIPTEN)
        list(APPEND BUILD_ARGS -p web)
    endif()

    set(ARCH "")
    if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
        set(ARCH "x86")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
        set(ARCH "x64")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm")
        set(ARCH "arm")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64")
        set(ARCH "arm64")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "wasm32")
        # For WebAssembly, use wasm-mt when threads are enabled, wasm when threads are disabled
        if("enable-threads" IN_LIST FEATURES)
            set(ARCH "wasm-mt")
            message(STATUS "Using multi-threaded WebAssembly architecture: ${ARCH}")
        else()
            set(ARCH "wasm")
            message(STATUS "Using single-threaded WebAssembly architecture: ${ARCH}")
        endif()
    endif()
    list(APPEND BUILD_ARGS -a ${ARCH})

    set(BUILD_TYPE_NAME "release")
    if(IS_DEBUG)
        set(BUILD_TYPE_NAME "debug")
    endif()
    
    vcpkg_execute_required_process(
        COMMAND ${NODEJS} ${BUILD_ARGS}
        WORKING_DIRECTORY "${SOURCE_PATH}"
        LOGNAME "tgfx-vendor-build-${BUILD_TYPE_NAME}"
    )
    
    if(ARCH)
        set(ARCH_DIR "${OUTPUT_DIR}/${ARCH}")
        if(EXISTS "${ARCH_DIR}")
            file(GLOB LIB_FILES "${ARCH_DIR}/*.a" "${ARCH_DIR}/*.lib")
            foreach(LIB_FILE ${LIB_FILES})
                get_filename_component(LIB_NAME "${LIB_FILE}" NAME)
                file(RENAME "${LIB_FILE}" "${OUTPUT_DIR}/${LIB_NAME}")
            endforeach()
            file(REMOVE_RECURSE "${ARCH_DIR}")
        endif()
    endif()
endfunction()

function(build_tgfx_with_vendor_tools SOURCE_PATH NODEJS)
    set(ENV{CMAKE_COMMAND} "${CMAKE_COMMAND}")
    set(ENV{CMAKE_PREFIX_PATH} "${CURRENT_INSTALLED_DIR}")
    message(STATUS "Building TGFX release version...")
    build_tgfx_single_config("${SOURCE_PATH}" "${NODEJS}" "${CURRENT_PACKAGES_DIR}/lib" FALSE)
    if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
        message(STATUS "Building TGFX debug version...")
        build_tgfx_single_config("${SOURCE_PATH}" "${NODEJS}" "${CURRENT_PACKAGES_DIR}/debug/lib" TRUE)
    endif()
endfunction()