/////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Tencent is pleased to support the open source community by making tgfx available.
//
//  Copyright (C) 2026 Tencent. All rights reserved.
//
//  Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
//  in compliance with the License. You may obtain a copy of the License at
//
//      https://opensource.org/licenses/BSD-3-Clause
//
//  unless required by applicable law or agreed to in writing, software distributed under the
//  license is distributed on an "as is" basis, without warranties or conditions of any kind,
//  either express or implied. see the license for the specific language governing permissions
//  and limitations under the license.
//
/////////////////////////////////////////////////////////////////////////////////////////////////

#include "UsfPackager.h"

namespace tgfx {

std::string PackageAsUsf(const std::string& hlslSource, GlslStage stage,
                         const std::string& keyHex) {
  std::string out;
  out += "// Generated by tools/glsl_to_usf for TGFX pipeline ";
  out += keyHex;
  out += "\n";
  out += "// Stage: ";
  out += (stage == GlslStage::Vertex) ? "vertex (entry: MainVS)" : "fragment (entry: MainPS)";
  out += "\n";
  out += "// Do not edit — regenerate with ./glsl_to_usf --input <dump> --output <dir>\n";
  out += "\n";
  out += "#include \"/Engine/Public/Platform.ush\"\n";
  out += "\n";
  out += hlslSource;
  // Ensure trailing newline so concatenated .usf files behave well.
  if (out.empty() || out.back() != '\n') {
    out += '\n';
  }
  return out;
}

}  // namespace tgfx
