name: autotest

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  autotest:
    runs-on: macos-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Get Environment Cache
        id: environment-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            /usr/local/Cellar/ninja
            /usr/local/Cellar/icu4c
            /usr/local/bin/ninja
            /usr/local/Cellar/yasm
            /usr/local/bin/yasm
            /usr/local/bin/depsync
            /usr/local/lib/node_modules/depsync
            /usr/local/Cellar/gcovr
            /usr/local/bin/gcovr
            /usr/local/Cellar/emsdk
            /usr/local/Cellar/emsdk/upstream/emscripten
            /usr/local/Cellar/emsdk/node/14.18.2_64bit/bin
            /usr/local/bin/em++
            /usr/local/bin/em-config
            /usr/local/bin/emar
            /usr/local/bin/embuilder
            /usr/local/bin/emcc
            /usr/local/bin/emcmake
            /usr/local/bin/emconfigure
            /usr/local/bin/emdump
            /usr/local/bin/emdwp
            /usr/local/bin/emmake
            /usr/local/bin/emnm
            /usr/local/bin/emrun
            /usr/local/bin/emprofile
            /usr/local/bin/emscons
            /usr/local/bin/emsize
            /usr/local/bin/emstrip
            /usr/local/bin/emsymbolizer
            /usr/local/bin/emcc.py
            /usr/local/bin/emcmake.py
            /usr/local/bin/emar.py
          key: tgfx-environment-macos-20231024

      - name: Get Third-Party Cache
        id: third-party-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            third_party
            vendor_tools
            test/baseline/.cache
          key: third-party-autotest-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}
          restore-keys: third-party-autotest-

      - name: Run depsync
        run: |
          chmod +x sync_deps.sh
          ./sync_deps.sh
        shell: bash

      - name: Check Code Format
        run: |
          chmod +x codeformat.sh
          ./codeformat.sh
        shell: bash

      - name: Run Autotest
        run: |
          chmod +x autotest.sh
          ./autotest.sh

      - name: Run Codecov
        run: |
          chmod +x codecov.sh
          ./codecov.sh

      - name: Upload Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: result/coverage.xml

      - name: Save Environment Cache
        if: ${{ (github.event_name == 'push') && (steps.environment-cache.outputs.cache-hit != 'true') }}
        uses: actions/cache/save@v3
        with:
          path: |
            /usr/local/Cellar/ninja
            /usr/local/Cellar/icu4c
            /usr/local/bin/ninja
            /usr/local/Cellar/yasm
            /usr/local/bin/yasm
            /usr/local/bin/depsync
            /usr/local/lib/node_modules/depsync
            /usr/local/Cellar/gcovr
            /usr/local/bin/gcovr
            /usr/local/Cellar/emsdk
            /usr/local/Cellar/emsdk/upstream/emscripten
            /usr/local/Cellar/emsdk/node/14.18.2_64bit/bin
            /usr/local/bin/em++
            /usr/local/bin/em-config
            /usr/local/bin/emar
            /usr/local/bin/embuilder
            /usr/local/bin/emcc
            /usr/local/bin/emcmake
            /usr/local/bin/emconfigure
            /usr/local/bin/emdump
            /usr/local/bin/emdwp
            /usr/local/bin/emmake
            /usr/local/bin/emnm
            /usr/local/bin/emrun
            /usr/local/bin/emprofile
            /usr/local/bin/emscons
            /usr/local/bin/emsize
            /usr/local/bin/emstrip
            /usr/local/bin/emsymbolizer
            /usr/local/bin/emcc.py
            /usr/local/bin/emcmake.py
            /usr/local/bin/emar.py
          key: tgfx-environment-macos-20231024

      - name: Save Third-Party Cache
        if: ${{ (github.event_name == 'push') && (steps.third-party-cache.outputs.cache-hit != 'true') }}
        uses: actions/cache/save@v3
        with:
          path: |
            third_party
            vendor_tools
            test/baseline/.cache
          key: third-party-autotest-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}

      - name: Job Failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result

      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: result
