name: autotest

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  mac-opengl:
    name: mac (opengl-swiftshader)
    runs-on: macos-14
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Get Third-Party Cache
        id: third-party-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            third_party
            test/baseline/.cache/opengl-swiftshader
          key: autotest-mac-opengl-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}
          restore-keys: autotest-mac-opengl-

      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: ninja yasm gcovr

      - name: Run depsync
        run: |
          npm install depsync -g
          depsync
        shell: bash

      - name: Check Code Format
        run: |
          chmod +x codeformat.sh
          ./codeformat.sh
        shell: bash

      - name: Run Autotest
        run: |
          chmod +x autotest.sh
          ./autotest.sh USE_OPENGL_SWIFTSHADER
        env:
          TRACY_NO_INVARIANT_CHECK: 1

      - name: Run Codecov
        run: |
          chmod +x codecov.sh
          ./codecov.sh

      - name: Upload Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: result/coverage.xml

      - name: Save Third-Party Cache
        if: ${{ (github.event_name == 'push') && (steps.third-party-cache.outputs.cache-hit != 'true') }}
        uses: actions/cache/save@v4
        with:
          path: |
            third_party
            test/baseline/.cache/opengl-swiftshader
          key: autotest-mac-opengl-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}

      - name: Upload Result
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: mac_opengl_result
          path: result

  mac-metal:
    name: mac (metal)
    runs-on: macos-14
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Get Third-Party Cache
        id: third-party-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            third_party
            test/baseline/.cache/metal
          key: autotest-mac-metal-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}
          restore-keys: autotest-mac-metal-

      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: ninja yasm

      - name: Run depsync
        run: |
          npm install depsync -g
          depsync
        shell: bash

      - name: Run Autotest
        run: |
          chmod +x autotest.sh
          ./autotest.sh USE_METAL
        env:
          TRACY_NO_INVARIANT_CHECK: 1

      - name: Save Third-Party Cache
        if: ${{ (github.event_name == 'push') && (steps.third-party-cache.outputs.cache-hit != 'true') }}
        uses: actions/cache/save@v4
        with:
          path: |
            third_party
            test/baseline/.cache/metal
          key: autotest-mac-metal-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}

      - name: Upload Result
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: mac_metal_result
          path: result

  mac-vulkan:
    name: mac (vulkan-swiftshader)
    runs-on: macos-14
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Get Third-Party Cache
        id: third-party-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            third_party
            test/baseline/.cache/vulkan-swiftshader
          key: autotest-mac-vulkan-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}
          restore-keys: autotest-mac-vulkan-

      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: ninja yasm

      - name: Run depsync
        run: |
          npm install depsync -g
          depsync
        shell: bash

      - name: Run Autotest
        run: |
          chmod +x autotest.sh
          ./autotest.sh USE_VULKAN_SWIFTSHADER
        env:
          TRACY_NO_INVARIANT_CHECK: 1

      - name: Save Third-Party Cache
        if: ${{ (github.event_name == 'push') && (steps.third-party-cache.outputs.cache-hit != 'true') }}
        uses: actions/cache/save@v4
        with:
          path: |
            third_party
            test/baseline/.cache/vulkan-swiftshader
          key: autotest-mac-vulkan-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}

      - name: Upload Result
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: mac_vulkan_result
          path: result

